# Order Service Specific Configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: order-group-v3

springdoc:
  api-docs:
    path: /api/orders/v3/api-docs
    servers:
      - url: https://gts-api.slpro.in
        description: GT Store API Gateway
  swagger-ui:
    enabled: true
