server:
  port: 4010

spring:
  application:
    name: notification-service
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-group-v3
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

# Custom notification config
notification:
  from-email: ${SMTP_FROM:noreply@slpro.in}
  cc-email: ${NOTIFICATION_CC:support@slpro.in}
  templates:
    ORDER_CONFIRMED: order-confirmed
    PAYMENT_SUCCESSFUL: payment-successful
    ORDER_DISPATCHED: order-dispatched
    ORDER_CANCELLED: order-cancelled
    ORDER_CANCELLED_BY_CUSTOMER: order-cancelled
    FULFILLMENT_FAILED: fulfillment-failed
    PAYMENT_FAILED: payment-failed
    AWAITING_FULFILLMENT: order-processing
    SUPPORT_ADMIN: support-admin
    SUPPORT_ACK: support-ack

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:4012/api/v2/spans
