server:
  port: 4003
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
      routes:
        - id: user-service
          uri: http://user-service:4004
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://product-service:4005
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: cart-service
          uri: http://cart-service:4006
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: http://order-service:4007
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
          uri: http://inventory-service:4008
          predicates:
            - Path=/api/inventory/**
        - id: payment-service
          uri: http://payment-service:4009
          predicates:
            - Path=/api/payments/**
        - id: search-service
          uri: http://search-service:4011
          predicates:
            - Path=/api/search/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://pahchaan.slpro.in/realms/e-pahchaan
          jwk-set-uri: https://pahchaan.slpro.in/realms/e-pahchaan/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:4012/api/v2/spans
