server:
  port: 8088

spring:
  application:
    name: search-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://pahchaan.slpro.in/realms/e-pahchaan
          jwk-set-uri: https://pahchaan.slpro.in/realms/e-pahchaan/protocol/openid-connect/certs
  elasticsearch:
    uris: http://elasticsearch:9200
    socket-timeout: 30s
    connection-timeout: 5s
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
