server:
  port: 8082
  forward-headers-strategy: native

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/gtstore_db
    username: gtstore
    password: password
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://pahchaan.slpro.in/realms/e-pahchaan
          jwk-set-uri: https://pahchaan.slpro.in/realms/e-pahchaan/protocol/openid-connect/certs

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
