server:
  port: 8083

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/gtstore_catalog?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/gt-store
          jwk-set-uri: http://keycloak:8080/realms/gt-store/protocol/openid-connect/certs

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
