server:
  port: 4005

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:password@host.docker.internal:27018/gtstore_catalog?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://pahchaan.slpro.in/realms/e-pahchaan
          jwk-set-uri: https://pahchaan.slpro.in/realms/e-pahchaan/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:4012/api/v2/spans

springdoc:
  api-docs:
    path: /api/products/v3/api-docs


