server:
  port: 8084

spring:
  application:
    name: cart-service
  data:
    redis:
      host: host.docker.internal
      port: 6379

logging:
  level:
    org.springframework.data.redis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
