server:
  port: 4006

spring:
  application:
    name: cart-service
  data:
    redis:
      host: host.docker.internal
      port: 6379
      password: ${REDIS_PASSWORD:khojo_redis_password}

logging:
  level:
    org.springframework.data.redis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:4012/api/v2/spans
